### ISSUE TITLE
Change Request

### ISSUE THREAD

**Issue by Nithisha-VK** [SyedAli017/Password-generator#1]
- [x] Indentation error in style.css file. Follow proper indentation
- [x]  Use classname for applying styles. so we can re-use it for same style. like  you don't have to define the style for both id's for #password-one and #password-two .you can define the style for one class name and re use it
- [x] when i continuously click the generate button it will broke the design and text will overflow

![image](https://user-images.githubusercontent.com/78464550/225906131-ea2626c4-6957-4bfd-9e58-0fa5b582dcbb.png)

-either you can use a reset button for clear the text

**Comment by SyedAli017** [comment]
Made the changes that you mentioned
